steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/docker-gcloud-make', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'eu.gcr.io/$PROJECT_ID/docker-gcloud-make', 'eu.gcr.io/$PROJECT_ID/docker-gcloud-make:$TAG_NAME']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/$PROJECT_ID/docker-gcloud-make']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/$PROJECT_ID/docker-gcloud-make:$TAG_NAME']

images: 
- 'eu.gcr.io/$PROJECT_ID/docker-gcloud-make'
- 'eu.gcr.io/$PROJECT_ID/docker-gcloud-make:$TAG_NAME'
